tasks:
  - name: chore
    before: >
      gp sync-await install &&
      nvm use default &&
      pnpm install-tools &&
      pnpm seed
    command: pnpm lint
  - name: app
    # Based on https://www.gitpod.io/docs/introduction/languages/javascript#node-versions
    before: >
      nvm install 18 &&
      nvm alias default 18 &&
      echo "nvm use default" >> ~/.bashrc.d/51-nvm-fix &&
      pnpm install &&
      gp sync-done install &&
      pnpm boot &&
      pnpm local-services start
    command: pnpm dev

ports:
  - name: app-server
    port: 4000
    onOpen: notify
    visibility: public
  - name: static-server
    port: 4444
    onOpen: notify
    visibility: public
  - name: development ports
    port: 4900-4999
    onOpen: ignore
  - name: test ports
    port: 4800-4899
    onOpen: ignore
